### ISSUE TITLE
'Downloads' in setting not working 

### ISSUE THREAD

**Issue by adilurrhmn** [Zenda-Cross/vega-app#101]
### Brief summary

Not working

![IMG_20240902_193733](https://github.com/user-attachments/assets/19aaf818-78dc-4c61-879f-971759d40ded)

### Vega version

2.4.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by himanshu8443** [comment]
device android version ?

**Comment by adilurrhmn** [comment]
Device: Realme GT Neo 3T 
Android: 14

**Comment by Shebyyy** [comment]
For me it opens a message app.

**Comment by D024kkk** [comment]
For me downloads button open notes app

**Comment by Zenda-Cross** [comment]
Lol, that's look bad, It should open file explorer.
I will try to fix it in the next update.
until then you can open it manually, downloaded videos are in downloads/vega folder

**Comment by adilurrhmn** [comment]
If possible, make it inside the app. I mean downloaded series and movies are playable from downloads option

**Comment by adilurrhmn** [comment]
One suggestion, 
Remove some unwanted websites.
Extramovies

**Comment by Zenda-Cross** [comment]
> One suggestion, Remove some unwanted websites. Extramovies

why is it not working?

**Comment by adilurrhmn** [comment]
They uses luxmovies, Vegamovies content. Name of the file also contains Vegamovies or luxmovies

**Comment by adilurrhmn** [comment]
> > One suggestion, Remove some unwanted websites. Extramovies
> 
> why is it not working anymore?

Replace Extramovies with https://bollyflix.wales/

Extramovies uses Vegamovies contents and old contents are not available shows blank

**Comment by Zenda-Cross** [comment]
I have removed the shortcut for downloading. I will create it again later.

**Comment by adilurrhmn** [comment]
Okay
