### ISSUE TITLE
Floating Button to Change provider

### ISSUE THREAD

**Issue by OshekharO** [Zenda-Cross/vega-app#102]
### Describe your suggested feature

Instead of Drawer to quickly change provider, how about adding floating button at bottom right of home like cloudstream.

Just an suggestion.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Zenda-Cross** [comment]
I just wanted to keep the homepage more clean.
But If you are facing any problem I can change that let me know

**Comment by OshekharO** [comment]
> I just wanted to keep the homepage more clean. But If you are facing any problem with drawer I can change that let me know

In gesture type navigation it becomes difficult to open side drawer atleast for me and people I know. Also the suggestion I made is good for both the type of navigation + ui wise also it's a good idea.

**Comment by Zenda-Cross** [comment]
Is it because the back button fires when trying to open the drawer? I tried to increase the edge width to fix that.
if you are still facing problems I can add a hamburger menu

**Comment by OshekharO** [comment]
> Is it because the back button fires when trying to open the drawer? I tried to increase the edge width to fix that. if you are still facing problems I can add a hamburger menu

Yeah sure, thanks do whatever you see fits

**Comment by Zenda-Cross** [comment]
hamburger menu added to open drawer. I can be enabled form settings
