### ISSUE TITLE
Search Not working 

### ISSUE THREAD

**Issue by adilurrhmn** [Zenda-Cross/vega-app#106]
### Brief summary

Please update luxmovies 
Searching movies or series shows not available, 
I tried with DNS on off.

### Vega version

2.4.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Zenda-Cross** [comment]
luxmovies search won't work because of cloudflare verification firewall

**Comment by adilurrhmn** [comment]
Okay 👍

**Comment by LEOATIQ** [comment]
Can u 123mkv and moviesmod
