### ISSUE TITLE
Continue watching feature 

### ISSUE THREAD

**Issue by NelsonGuiamba** [Zenda-Cross/vega-app#116]
### Describe your suggested feature

Firstly I would like to thank you for your incredible app it is working smoothly in my low end device (A53 4 core armv7)
But It could be better if we can have a page to continue watching films movies etc from whenever we stop 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by himanshu8443** [comment]
Firstly, thank you very much. 
There is a feature that displays the most recently watched videos; it can be enabled from the settings, and also the player will resume the video from where it was last left off.

**Comment by Zenda-Cross** [comment]
Firstly, thank you very much. 
There is a feature that displays the most recently watched videos; it can be enabled from the settings, and also the player will resume the video from where it was last left off.

**Comment by NelsonGuiamba** [comment]
Great, Yesterday I noticed that the player continued from where it stop (even after crashing ) but you need to open the movie from the provider you were watching. However you can close this issue now
