### ISSUE TITLE
Can't skip forward in the timeline

### ISSUE THREAD

**Issue by C0smic-Ventures** [Zenda-Cross/vega-app#119]
### Brief summary

I can't skip forward/press the +10 or - 10 buttons without it reverting to the start of the movie. I Noticed that this is only True in some downloaded movies. 

### Vega version

2.4.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by himanshu8443** [comment]
can you share the movie name and provider name

**Comment by Zenda-Cross** [comment]
no reply
