### ISSUE TITLE
Can you add MX Player/ MX player Pro Support

### ISSUE THREAD

**Issue by iamfree139** [Zenda-Cross/vega-app#12]

**Comment by Zenda-Cross** [comment]
sure, if I could find its URI scheme or intent

**Comment by Zenda-Cross** [comment]
@iamfree139 MX player support is added in the beta version for now [download](https://github.com/Zenda-Cross/vega-app/releases/tag/v1.3.6) 
If you are able to test, I will close the issue and release it as stable.
