### ISSUE TITLE
Request for movie site

### ISSUE THREAD

**Issue by Soby370** [Zenda-Cross/vega-app#124]
### Describe your suggested feature

Kindly this movie website too if possible
https://zinkmovies.one/
Thanks in advance

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by godsgiftex** [comment]
You can add new servers in movies and webseries like -

https://pahe.ink/
https://katmoviehd.fi/
https://katmovie4k.net/

https://themoviesboss.click/

https://bollyflix.beer/

https://mkvcinemas.cat/

https://1moviesfd.skin/

And if you get olamovies servers please add

And for anime - use

https://hianime.to/

https://zoroxtv.to/

https://aniwatchtv.to/home


You can work on your app logo that refers that you have changed the api

Use search engine more optimized

Make a login ID or registration feed and also use wishlist , make all
movies released year refine and visible.

Make all server provider names visible on your hamburger menu and server
menu that will be helpful.


I appreciate your great work and one the best API &  user interface.
