### ISSUE TITLE
Indonesian subtitle

### ISSUE THREAD

**Issue by fawzydede** [Zenda-Cross/vega-app#127]
### Describe your suggested feature

Can you please add Bahasa Indonesia (ind) in the online subtitle search?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Zenda-Cross** [comment]
sure

**Comment by Zenda-Cross** [comment]
added check https://github.com/Zenda-Cross/vega-app/releases/tag/v2.4.7
