### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by D024kkk** [Zenda-Cross/vega-app#129]
### Brief summary

Please add **Autoembed movies server** because when it was available early it was working well so please add that server ,

And some servers like Hdhub4u , vegamovies , luxmovies , multimovies , world4ufree  , these are not working please fix them

### Vega version

2.4.6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by himanshu8443** [comment]
Autoembed  is working in multistream
vegamovies , luxmovies , multimovies are working
multimovies  website is not working
I will try to fix world4ufree

**Comment by D024kkk** [comment]
Please separate Autoembed server from multistream , If only this can happen then. 
And thank you in advance

**Comment by Zenda-Cross** [comment]
I can't create new provider for every server 
I'll try what I can do
