### ISSUE TITLE
Server and ui

### ISSUE THREAD

**Issue by Monuk2744** [Zenda-Cross/vega-app#130]
### Brief summary

Vegamovie and other providers not working on mobile network like 
JIO fix these issue 

Make app interface like steamflix app ui for Android tv

### Vega version

4.6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Zenda-Cross** [comment]
I have updated the domain of providers if it is still not working on mobile networks means your ISP has banned their domains 
also app doesn't support tv
