### ISSUE TITLE
Whenver i play any movie or video it says video could not be played try again later

### ISSUE THREAD

**Issue by Shubham6578** [Zenda-Cross/vega-app#137]
### Brief summary

![Screenshot_20241020_103319_Vega](https://github.com/user-attachments/assets/03426763-6f66-4754-aa57-306d89199b24)

### Vega version

Latest

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Zenda-Cross** [comment]
is this happening for every movie in every provider ?

**Comment by Shubham6578** [comment]
> is this happening for every movie in every provider or a particular provider ?

Its is happing in many movies and mamy providers

**Comment by Shubham6578** [comment]
> If you're experiencing issues with some older movies, that's normal and can't be fixed. These problems often arise because the links provided by the streaming services may be outdated or broken. In your example, the movie "Alone" on Dooflix isn't playing because the link is no longer working, which is an issue on their end.

I am getting isue on some new mamy movies and many providers pls help

**Comment by Zenda-Cross** [comment]
can you give more examples
movie names with provider name
