### ISSUE TITLE
Introduce Log In Option 

### ISSUE THREAD

**Issue by adilurrhmn** [Zenda-Cross/vega-app#143]
### Describe your suggested feature

Please Introduce Login option that helps us to saved bookmark, watch history etc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Zenda-Cross** [comment]
for that I have to create a separate backend and database
I can add a export and import feature to backup

**Comment by adilurrhmn** [comment]
Backup export import is time consuming and sometimes we forgot to create backups. Thats why login will more useful.
Its your call, Think about it, If you can then introduce it please 🥺

**Comment by Zenda-Cross** [comment]
may be later in the future
