### ISSUE TITLE
Add steaming server option

### ISSUE THREAD

**Issue by Monuk2744** [Zenda-Cross/vega-app#152]
### Describe your suggested feature

Add streaming server option while play like download option

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Zenda-Cross** [comment]
I didn't understand what you meant.

**Comment by Monuk2744** [comment]
When we play a movie then apply the server option like download

**Comment by himanshu8443** [comment]
you can change server form player

**Comment by himanshu8443** [comment]
if you want to change server for an external player hold the download button, a pop like download will appear and click on the desired server to play

**Comment by himanshu8443** [comment]
Don't long press on server button, long press the actual download button
I am not telling you to copy and past the link, it will open the player selecting menu

**Comment by Monuk2744** [comment]
👍 thanks bro it's works
