### ISSUE TITLE
Moviesapi

### ISSUE THREAD

**Issue by phisher98** [Zenda-Cross/vega-app#153]
### Brief summary

Moviesapi not playing any content

### Steps to reproduce

Play Moviesapi not playing any content

### Vega version

2.5.4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Zenda-Cross** [comment]
I am tired of fixing that, they change their code almost every week
Maybe I will just remove it.

**Comment by phisher98** [comment]
They may have changed their encryption this time buddy can you have a look at it ?
