### ISSUE TITLE
Option to remove useless video gestures on the player 

### ISSUE THREAD

**Issue by Uvdon** [Zenda-Cross/vega-app#156]
### Brief summary

Title says it all. God, I can't express how much I hate these stupid bloated gestures in a video player, it literally takes less than 1 sec on your phone to change brightness/volume on your phone and I will never understand how people are that lazy. Not only is this a problem, but when I go back to home screen from watching a content, the brightness gets so high it hurts my eyes and I can't do nothing but shut down the app and reopen it. I'm not saying remove it, but give users like me to turn it off god damn

### Vega version

2.5.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Zenda-Cross** [comment]
No worries, I get it!

**Comment by Zenda-Cross** [comment]
option added #161

**Comment by Uvdon** [comment]
Thank you much appreciated!
