### ISSUE TITLE
Server request 

### ISSUE THREAD

**Issue by Uvdon** [Zenda-Cross/vega-app#157]
### Describe your suggested feature

Hello. Can you please add ridomovies server from cloud-stream. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Zenda-Cross** [comment]
can you share the website url

**Comment by Uvdon** [comment]
https://ridomovies.tv/

**Comment by NarendraY1** [comment]
Hello, your work is amazing 🤩. Can you please add olamovies. And can you refine or update Android tv app. 

https://app1.olamovies.download/

Again thank you so much 🙏😌

**Comment by himanshu8443** [comment]
ola movies is not possible they use Cloudflare human verification firewall

**Comment by NarendraY1** [comment]
Can you update vega tv app, when i install vega v2.5.5 in my Chromecast then videa didn't play, and then i install vega tv 2.3.0 its then say update the app.

**Comment by Zenda-Cross** [comment]
tv app is discontinued
