### ISSUE TITLE
Webview not working

### ISSUE THREAD

**Issue by rajbhanushali97** [Zenda-Cross/vega-app#162]
### Brief summary

Webview or Open in Browser for many providers is not working doesn't loads the website just blank page or says preety print for example multistream guardahd dramacool please check and fix 

### Vega version

2.5.6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Zenda-Cross** [comment]
that's because not all providers are website
some are api and required specific headers to pass the request
