### ISSUE TITLE
Pause and Resume

### ISSUE THREAD

**Issue by D024kkk** [Zenda-Cross/vega-app#164]
### Describe your suggested feature

Please add the Pause ⏸️ and Resume feature in download 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by D024kkk** [comment]
I am talking about downloading 
Please add pause and resume feature in Downloading

**Comment by Zenda-Cross** [comment]
Oh
Though most providers don't support resume on download because link expires after few hours
but it's still in the roadmap
