### ISSUE TITLE
App not working on mobile network

### ISSUE THREAD

**Issue by Monuk2744** [Zenda-Cross/vega-app#166]
### Brief summary

The apps from the mobile service provider are not working and I am unable to access any website.

### Vega version

2.5.6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by himanshu8443** [comment]
That's because your ISP blocked the domain of providers not an app issue

**Comment by D024kkk** [comment]
Use VPN

**Comment by Monuk2744** [comment]
By using VPN the speed will be slow and I am using Jio 5G

**Comment by Zenda-Cross** [comment]
Can't do anything about it
try changing dns it works most of the time
