### ISSUE TITLE
Features 

### ISSUE THREAD

**Issue by Zain436724** [Zenda-Cross/vega-app#176]
### Describe your suggested feature

I really appreciate the effort you’ve put into offering free streaming.
I was wondering if you could consider adding features like sorting by latest etc, filtering by year etc, or enhancing categories. It would make finding content even easier and improve the overall experience.
Thanks again for the amazing app!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Zenda-Cross** [comment]
Not possible because content is scrapper directly from respective providers website and most of them not provide these features

**Comment by NarendraY1** [comment]
Can you add a different section for downloads or one click complete series download?

**Comment by Zenda-Cross** [comment]
> Can you add a different section for downloads or one click complete series download?

problem is server selection app can't choose it automatically so that's why they is no feature for multiple episodes download

**Comment by Zain436724** [comment]
Thanks Team for the info :)
