### ISSUE TITLE
Add Anime Sources

### ISSUE THREAD

**Issue by iamfree139** [Zenda-Cross/vega-app#21]
Most sources don't have anime, and some that do only offer popular ones like Naruto, etc. By adding new anime sources, it will give users more variety of content to watch.

**Comment by Zenda-Cross** [comment]
ok,
I'm considering, adding tokyoinsider.com

**Comment by iamfree139** [comment]
Tokyo Insider does not offer popular anime like Attack on Titan (though it can be found on other providers). For a centralized place for anime, we should consider alternatives, as Tokyo Insider mostly features older anime series.

**Comment by Zenda-Cross** [comment]
ok, I will add gogoanime

**Comment by iamfree139** [comment]
That would be great.
