### ISSUE TITLE
Site Request

### ISSUE THREAD

**Issue by adilurrhmn** [Zenda-Cross/vega-app#22]
Loved it. Thank you for this one ❤️‍🩹. 
One request can you add 'mkvcinemas'

**Comment by Zenda-Cross** [comment]
> Loved it. Thank you for this one ❤️‍🩹. 
Thank you so much 🫡

> One request can you add 'mkvcinemas'
Sorry,I can't add 'mkvcinemas' beecause it uses cloudfare protection which prevents me from scraping its links .

**Comment by adilurrhmn** [comment]
Okay... Thank you 😊
