### ISSUE TITLE
No stream found ( Vegamovies)

### ISSUE THREAD

**Issue by adilurrhmn** [Zenda-Cross/vega-app#23]
![Screenshot_2024-06-09-11-22-00-76_11fe5ff35dd1fae673697ec5eb78287f](https://github.com/Zenda-Cross/vega-app/assets/124466769/acb027ea-15ef-450d-93b1-ab76e80ca89f)

**Comment by Zenda-Cross** [comment]
what show/movie is this

**Comment by adilurrhmn** [comment]
Every movies and tv shows

**Comment by Zenda-Cross** [comment]
that was because they changed site domain should be working now

**Comment by Zenda-Cross** [comment]
Check out the new update that fixes the issue more appropriately.

**Comment by adilurrhmn** [comment]
Yes. Working now
