### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by adilurrhmn** [Zenda-Cross/vega-app#25]
Can you please change the Player,  Doesn't support full screen. I am attaching screenshot of two other player.

1st one is Vega Player 
Remaining two are suggestion 

![IMG_20240609_150935](https://github.com/Zenda-Cross/vega-app/assets/124466769/0f8caad6-9962-4da3-8683-cc780a3eab49)

![Screenshot_2024-06-09-15-05-12-77_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Zenda-Cross/vega-app/assets/124466769/5b73ad30-9d83-4d93-b273-9f8db5f2f884)

![Screenshot_2024-06-09-14-47-02-96_cfa2fd239c8cded9285432912d0e0818](https://github.com/Zenda-Cross/vega-app/assets/124466769/19ff1b13-d90e-40a1-b525-f3de8a9ae8e5)

**Comment by adilurrhmn** [comment]
And one another beautiful player

Its Drive stream Player

https://github.com/itszechs/DriveStream


![Screenshot_2024-06-09-15-47-49-51_f7a0fc1b6f097aba13f74e71f9ef590d](https://github.com/Zenda-Cross/vega-app/assets/124466769/b9d503fe-6cdd-4d28-b305-27c0e28713ec)

**Comment by Zenda-Cross** [comment]
The problem is this app is made with [React Native](https://reactnative.dev/), So I can't use other apps players and the player used here is the only player available for React native.
I will try to fix the full-screen problem and improve it.
