### ISSUE TITLE
New request 

### ISSUE THREAD

**Issue by adilurrhmn** [Zenda-Cross/vega-app#26]
Can you add torrent sites like torrent galaxy, 1337x.
Its easy for us for streaming movies and series

**Comment by Zenda-Cross** [comment]
Not sure, but maybe in the future, because it's different from other sources, torrent streaming works a little differently, so extra changes are needed.
And there is already Stremio.

**Comment by adilurrhmn** [comment]
I don't want to use stremio, Your UI is much better.. just upgrade your player.

**Comment by adilurrhmn** [comment]
And download speed very slow, 2mb/sec

**Comment by Zenda-Cross** [comment]
> And download speed very slow, 2mb/sec

where in vega?

**Comment by adilurrhmn** [comment]
Ok

**Comment by Uvdon** [comment]
> I don't want to use stremio, Your UI is much better.. just upgrade your player.

The video player is nice. No need for stupid gestures

**Comment by adilurrhmn** [comment]
I am saying that is doesn't support fullscreen  ... Just make it possible... No need to change the Player

**Comment by Uvdon** [comment]
Nothing works lol. Maybe just new content.

**Comment by Zenda-Cross** [comment]
> Nothing works lol. Maybe just new content.

yeah vegamovies increased protection and suddenly CfWorker links not working which are used by most providers

**Comment by pankajprasad337** [comment]
I really loved your app 👍🫡🙌🙌🙌 
A small request can you please add olamovies site 🙂.

**Comment by adilurrhmn** [comment]
> I really loved your app 👍🫡🙌🙌🙌 A small request can you please add olamovies site 🙂.
Olamovies can't be added

**Comment by pankajprasad337** [comment]
Mkvcinema can be added ??

**Comment by Zenda-Cross** [comment]
> I really loved your app 👍🫡🙌🙌🙌

thanks

sorry it's not possible to add 'Olamovies' and 'Mkvcinema'.

**Comment by adilurrhmn** [comment]
May be these two sites possible....

https://bolly4u.wales/
https://extramovies.ist/

**Comment by Zenda-Cross** [comment]
@adilurrhmn I wll try

**Comment by Uvdon** [comment]
Nah, add sora stream

**Comment by adilurrhmn** [comment]
Please Add 
https://extramovies.ist/

Most of the time, Vegamovies and Luxmovies do not work.

**Comment by Zenda-Cross** [comment]
@adilurrhmn OK wait for the next update.

**Comment by adilurrhmn** [comment]
Thank you for adding 
https://extramovies.ist/
New uploaded movies and series playing smoothly But old movies and series are not playing 
![Screenshot_2024-07-03-07-49-35-90_11fe5ff35dd1fae673697ec5eb78287f](https://github.com/Zenda-Cross/vega-app/assets/124466769/bfcca42a-29d1-4500-a036-2017190c4f00)

**Comment by Zenda-Cross** [comment]
most of the old links are not streamable

**Comment by adilurrhmn** [comment]
My last request.
 Can you add this website 
https://protonmovies.xyz/
 If possible... Then add this

**Comment by Zenda-Cross** [comment]
@adilurrhmn can't because of Cloudflare captcha protection

**Comment by adilurrhmn** [comment]
Okay.... Thank you 🤩

**Comment by adilurrhmn** [comment]
Add this site too...

Streaming site.... Many different sources are added 
https://www.primewire.tf/

**Comment by adilurrhmn** [comment]
Modmovies no stream found.
Its name changed. Now it is moviesmod
https://moviesmod.band/

Please update it

**Comment by Zenda-Cross** [comment]
> Modmovies no stream found. Its name changed. Now it is moviesmod https://moviesmod.band/

It has already been updated are you still getting not stream found?




> Add this site too...

The problem with Topmovies for many movies and series it only provides g-drives link and g-drive links can't be streamed
And I will check out Primewire it looks good.

**Comment by adilurrhmn** [comment]
> > Modmovies no stream found. Its name changed. Now it is moviesmod https://moviesmod.band/
> 
> It has already been updated are you still getting not stream found?
> 
> > Add this site too...
> 
> The problem with Topmovies for many movies and series it only provides g-drives link and g-drive links can't be streamed And I will check out Primewire it looks good.

![IMG_20240729_092806](https://github.com/user-attachments/assets/c38e8127-6c4f-48a2-b8bf-69eb093d9758)

**Comment by Zenda-Cross** [comment]
@adilurrhmn That is happening for some movies because it's using a different kind of link redirect and can only be fixed by update

**Comment by adilurrhmn** [comment]
Ok, thank you... And please work on primewire 🙏
