### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by aneesh1122** [Zenda-Cross/vega-app#30]
1) ability to select a region to get new releases based on that region.

2) add 'list view' because in the grid view the whole name of the movie is not visible.

3) add an option to sort by date released.

4) I don't know if it's possible but it would be cool if this was implemented :

Instead of searching for a movie in all the Sites, 

search a movie -> select that movie -> list out all the sites where that movie is available

**Comment by Zenda-Cross** [comment]
I apologize, but it's not practically possible. Different websites yield different search results, and the movie you're targeting could be located at various positions at each provider. And also  they don't provide enough information to sort the results.

**Comment by aneesh1122** [comment]
> I apologize, but it's not practically possible. Different websites yield different search results, and the movie you're targeting could be located at various positions at each provider. And also  they don't provide enough information to sort the results.

Could you please try the 1st and 2nd request if it's possible?

**Comment by Zenda-Cross** [comment]
@aneesh1122 ok I can grid view but getting
region based releases is not possible because websites don't provide info about region of movies.

**Comment by aneesh1122** [comment]
> @aneesh1122 ok I can grid view but getting
> region based releases is not possible because websites don't provide info about region of movies.

I want the 'list view'. The grid view is already there but the whole name of the movie is not visible in that mode

![IMG_20240622_100132.jpg](https://github.com/Zenda-Cross/vega-app/assets/45353488/5e4b3e6f-b4b6-49c4-be97-9c86d5e741a8)


Thanks for considering my request

**Comment by Zenda-Cross** [comment]
ahh sorry typo mistake I meant list view
