### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Fxrrcrxdsccexxe** [Zenda-Cross/vega-app#32]
Plz make app compatible in armeabi v7a devices

**Comment by Zenda-Cross** [comment]
it's universal build it should be compatible with armeabi-v7a devices

**Comment by Fxrrcrxdsccexxe** [comment]
But when I install app and open the app , app got crash 😕and send into home screen

**Comment by Zenda-Cross** [comment]
This is only armeabi-v7a build, you can check if it works?

https://drive.google.com/file/d/1tfLEW72eOpWDNxZil6N3Hbjs_xmPennr/view?usp=sharing

**Comment by punisher-303** [comment]
> This is only armeabi-v7a build, if you want to try.
> 
> https://drive.google.com/file/d/1tfLEW72eOpWDNxZil6N3Hbjs_xmPennr/view?usp=sharing

NOT WORKING ON arneabi-v7a devices it's crashing all the times

**Comment by Fxrrcrxdsccexxe** [comment]
Always crash

**Comment by Zenda-Cross** [comment]
@Fxrrcrxdsccexxe  @punisher-303 

Now should be working arneabi-v7a devices check the latest release.
https://github.com/Zenda-Cross/vega-app/releases
