### ISSUE TITLE
Problems in the pre-release

### ISSUE THREAD

**Issue by aneesh1122** [Zenda-Cross/vega-app#37]
1) first of all, thank you for adding the list view. It's working perfectly except for one problem

![Screenshot_2024-07-07-12-16-21-647_com.vega-edit.jpg](https://github.com/Zenda-Cross/vega-app/assets/45353488/103980e2-5684-4855-abc0-f8ab9d75a99b)

Pls add some padding at the bottom

2) vega movies isn't working. I'm able to get the results and open the movie's page but when I select 'more' this is what I get

https://github.com/Zenda-Cross/vega-app/assets/45353488/5360f3b3-33a3-48bb-91f3-cdc41cdbdae7

**Comment by Zenda-Cross** [comment]
thank you for testing pre-release
I will fix these problems
