### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by A-d-i-t-h-y-a-n** [Zenda-Cross/vega-app#40]
>npm run android

> vega@2.1.3 android
> react-native run-android

* daemon not running; starting now at tcp:5037
* daemon started successfully
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'C:\Users\HP\vega-app\android\settings.gradle' (C:\Users\HP\.gradle\caches\8.6\scripts\e17v1rd8tj7ca3mbrg9bjcfij).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 66

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 18s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong: Could not open settings generic class cache for settings file 'C:\Users\HP\vega-app\android\settings.gradle' (C:\Users\HP\.gradle\caches\8.6\scripts\e17v1rd8tj7ca3mbrg9bjcfij). > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 66 * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 18s.
info Run CLI with --verbose flag for more details.

**Comment by Zenda-Cross** [comment]
is your emulator running?
or is your Android connected with  USB debugging on?

**Comment by adithyan-hermit** [comment]
> is your emulator running? or is your Android device connected with USB debugging on?

With USB debugging

**Comment by A-d-i-t-h-y-a-n** [comment]
> is your emulator running? or is your Android device connected with USB debugging on?

With USB debugging

**Comment by Zenda-Cross** [comment]
There are two ways to run a debug app:

1. First, use the Android Studio emulator. The emulator should be running.
2. Second, use your physical Android device connected via USB. USB debugging should be enabled, and some devices may also require 'Install app over USB' to be turned on.
