### ISSUE TITLE
A small request

### ISSUE THREAD

**Issue by aneesh1122** [Zenda-Cross/vega-app#41]
Thanks for fixing the padding issues in list view.

Whenever I open a collection and switch to 'List view' and go back and reenter, it goes back to 'grid view'

Please make the 'List view' persistent. It should go back to grid view only when we switch the layout ourselves.

**Comment by Zenda-Cross** [comment]
ok, next update?

**Comment by aneesh1122** [comment]
> ok, in next update.

Thanks
