### ISSUE TITLE
Unsupported: MX Player Pro After Latest Update

### ISSUE THREAD

**Issue by iamfree139** [Zenda-Cross/vega-app#42]
Previously, MX Player Pro was supported, but after the latest update, it is no longer supported.

**Comment by Zenda-Cross** [comment]
Well, I initially created it to support only the non-pro version from the beginning. I didn't understand how it was functioning until the previous update, and I didn't make any changes related to it.

**Comment by iamfree139** [comment]
My bad, I thought it did, but yesterday when I was testing it on a new device, it didn't. Can you add support for the MX Player Pro version?
