### ISSUE TITLE
Auto-update option in settings

### ISSUE THREAD

**Issue by iamfree139** [Zenda-Cross/vega-app#43]
Updating it manually from GitHub each time is quite tedious; it would be convenient if there were an option for it to auto-update itself. This feature in the settings would greatly enhance the user experience.

**Comment by Zenda-Cross** [comment]
okay

**Comment by iamfree139** [comment]
Thanks, man. Once I've learned how to code, I will definitely contribute.

**Comment by iamfree139** [comment]
It still redirects to GitHub. I meant it auto-updates without any user intervention.

**Comment by Zenda-Cross** [comment]
Yes, I understood that you wanted to automatically download and install updates, but I was unable to do so .
I will add that feature if I am able to fix the errors.

**Comment by iamfree139** [comment]
whenever it's possible, thank you.

**Comment by Zenda-Cross** [comment]
option added #60
