### ISSUE TITLE
Hello can u pls put kissasian as provider so that we can watch asian series too? Nd can u add 360p download option too?

### ISSUE THREAD

**Issue by Aruraka** [Zenda-Cross/vega-app#54]

**Comment by Zenda-Cross** [comment]
I can add Dramacool ?
using [Consumet ](https://github.com/consumet/api.consumet.org)and maybe it won't support 360p download but I will try.

**Comment by Aruraka** [comment]
> I can add Dramacool ? using [Consumet ](https://github.com/consumet/api.consumet.org)and maybe it won't support 360p download but I will try.

Thanks so much

**Comment by Aruraka** [comment]
> I can add Dramacool ? using [Consumet ](https://github.com/consumet/api.consumet.org)and maybe it won't support 360p download but I will try.

Adding dramacool will b the best

**Comment by Aruraka** [comment]
Can u inform me here after ur done with adding dramacool nd download option of 360p if possible?

**Comment by himanshu8443** [comment]
yes, I will inform and mark the issues as complete after its complete.

**Comment by Aruraka** [comment]
> yes, I will inform and mark the issues as complete after its complete.

Ok sure

**Comment by Zenda-Cross** [comment]
Added DramaCool check out the latest release.
Currently only download the highest quality.

**Comment by Aruraka** [comment]
> Added DramaCool check out the latest release. Currently only download the highest quality.

Okay thanks a lot
