### ISSUE TITLE
Hello ,i downloaded the app again but dramacool subtitles r overlapping can u pls add kissasian subtitles? It would fix the problem then

### ISSUE THREAD

**Issue by Aruraka** [Zenda-Cross/vega-app#55]

**Comment by Zenda-Cross** [comment]
How subtitles are overlapping can send a screenshot or video. when I checked it seems fine.

**Comment by Aruraka** [comment]
> How subtitles are overlapping can send a screenshot or video. when I checked it seems fine.

Well I can't record as I don't have recorder nd the subtitles r overlapping a bit in a series called as beautiful as you last episode nd also after I download nd click on the downloaded videos nothing is appearing it's appearing blank :))

**Comment by Zenda-Cross** [comment]
sorry but dramacool subtitles can not be changed as they are encoded in the video itself so using external subtitles can't help.
I hope you can manage with it if it's just for one series.
And I tried downloading episode 40.5 of "As Beautiful As You" and it's working well for me. Can you double-check if you downloaded the correct version of the app for your device?

**Comment by Aruraka** [comment]
> sorry but dramacool subtitles can not be changed as they are encoded in the video itself so using external subtitles can't help. I hope you can manage with it if it's just for one series. I will try adding more sources in future. And I tried downloading episode 40.5 of "As Beautiful As You" and it's working well for me. Can you double-check if you downloaded the correct version of the app for your device?

Oh that's okay yes I downloaded latest version only nd im having problems with download issue it's saying download failed

**Comment by Zenda-Cross** [comment]
Which server are you using currently only their server 1 is working.
and try downloading the universal version apk from latest releases.

**Comment by Aruraka** [comment]
> Which server are you using currently only their server 1 is working. and try downloading the universal version apk from latest releases.

I used server 1 only tho btw do u have discord by any chance? So that I can inform u about the problems if I face in this app?

**Comment by Zenda-Cross** [comment]
> I used server 1 only tho btw do u have discord by any chance? So that I can inform u about the problems if I face in this app?

Not now but I think should create one.
I will send you an invitation after creating it.

**Comment by Aruraka** [comment]
> > I used server 1 only tho btw do u have discord by any chance? So that I can inform u about the problems if I face in this app?
> 
> Not now but I think should create one. I will send you an invitation after creating it.

Okk sure

**Comment by Zenda-Cross** [comment]
https://discord.gg/cr42m6maWy

**Comment by Aruraka** [comment]
> https://discord.gg/cr42m6maWy

Okay I joined thanks 😊
