### ISSUE TITLE
Issue with APK

### ISSUE THREAD

**Issue by rajbhanushali97** [Zenda-Cross/vega-app#57]
Facing App crash issue on Android 14 after every few seconds or min of play and please add Continue watching/ Recent Watch list

**Comment by Zenda-Cross** [comment]
are you using correct version for your device ?

**Comment by rajbhanushali97** [comment]
Yea its arm64 v8a could it be server issues like i guess playing video cfworker threw me out while playing movie in few minutes but pixeldrain played well. sorry if am mistaken

**Comment by Zenda-Cross** [comment]
Is the app crashing or is it just throwing out of the player?

**Comment by rajbhanushali97** [comment]
App gets closed completely again have to open search and play (tho it resumes from last played)

**Comment by Harsh74170** [comment]
When I search anything in app it doesn't show any result in vegamovies section while the content is present on website but it is not shown here pls check it

**Comment by Zenda-Cross** [comment]
@Harsh74170  Vegamovies and Modmovies are too clever they have added Cloudflare firewall on the search route, so it's not possible to search.

**Comment by Harsh74170** [comment]
> @Harsh74170  Vegamovies and Modmovies are too clever they have added Cloudflare firewall on the search route, so it's not possible to search.

Ohh ok
Is there anyway to play movies directly in app through website otherwise how can I search?

**Comment by Zenda-Cross** [comment]
> Is there anyway to play movies directly in app through website otherwise how can I search?

currently, only way is using other providers.

**Comment by Harsh74170** [comment]
I was using app in a tablet I am facing issues in player it is not responding movie is not moving forward with the help of pointer

**Comment by Zenda-Cross** [comment]
> I was using app in a tablet I am facing issues in player it is not responding movie is not moving forward with the help of pointer

is the seek bar not working?

**Comment by Harsh74170** [comment]
Yes

**Comment by Harsh74170** [comment]
And to increase video size that option is also.not.working

**Comment by Zenda-Cross** [comment]
> And to increase video size that option is also.not.working

is it happening with all providers' videos?
are you using the correct version of the app for your device?
and which device are you using?

**Comment by Harsh74170** [comment]
I am using samsung a9 tab and I am using universal version and I am facing this issue in all providers

**Comment by Harsh74170** [comment]
And I have tried all other versions also

**Comment by Zenda-Cross** [comment]
@Harsh74170  I wasn't able to reproduce your issue but working on it until then try using external player.
And Vegamovies search not working is fixed.

**Comment by Harsh74170** [comment]
Ok thanks

**Comment by Zenda-Cross** [comment]
@Harsh74170  seek bar not working issue fixed

**Comment by Harsh74170** [comment]
> @Harsh74170  seek bar not working issue fixed

Thank you very much 😊

**Comment by Hammer-123768** [comment]
Please fix the "Cf worker" server on the app, because this servers works 10 to 15 days ago but now it's not working
Please fix this server
v3.2.0
