### ISSUE TITLE
Site request

### ISSUE THREAD

**Issue by AsfandYar1211** [Zenda-Cross/vega-app#61]
https://www.rgshows.me/?p=1
Can you plz add this source ..it would be amazing

**Comment by Zenda-Cross** [comment]
It's a VidSrc wrapper not an actual site

**Comment by AsfandYar1211** [comment]
Yeah ..but rgshows named server contains hindi dubbed material thats not in vidsrc.

**Comment by Zenda-Cross** [comment]
Do you mean "rgshows.me 3" sever?
that's allmovieland wrapper, yes I am planning to add it in future

**Comment by AsfandYar1211** [comment]
Ah ...i see ..And also rgshows.me 1 & 2.

**Comment by adilurrhmn** [comment]
Are you working on 
https://www.primewire.tf ?

**Comment by Zenda-Cross** [comment]
@adilurrhmn no not yet.

**Comment by adilurrhmn** [comment]
> @adilurrhmn no not yet.

Thanks for adding primewore. It support only one server - mixdrop 

Please add others sources like streamwish etc

**Comment by RISHAB-CREATOR** [comment]
> Do you mean "rgshows.me 3" server? that's from allmovieland , yes I am planning to add it in future

 BRO ITS YOUR OWN API :> 
I M THANKING U TILL THIS DATE FOR THAT API :)

**Comment by Zenda-Cross** [comment]
@RISHAB-CREATOR thanks
