### ISSUE TITLE
Seek bar is not working 

### ISSUE THREAD

**Issue by D024kkk** [Zenda-Cross/vega-app#64]
Seek bar is not working, I can't move forward in app

**Comment by Zenda-Cross** [comment]
what device are you using?

**Comment by D024kkk** [comment]
Redmi Pad Tablet

**Comment by Zenda-Cross** [comment]
are forward and rewind button working good ?

**Comment by D024kkk** [comment]
Yes , but slow

**Comment by D024kkk** [comment]
Seek bar and expand button is not working, please fix 🙏🙏

**Comment by Zenda-Cross** [comment]
ok

**Comment by Zenda-Cross** [comment]
so when you click on seek bar nothing happens right?
not even seek bar moving

**Comment by D024kkk** [comment]
Yes , it seems like it doesn't even exist

**Comment by Zenda-Cross** [comment]
ok, it will be fixed in the next update 
can you test apk before releasing the update to confirm its fixed

**Comment by D024kkk** [comment]
Absolutely

**Comment by Zenda-Cross** [comment]
https://github.com/Zenda-Cross/vega-app/releases/tag/v2.2.4
let me know if issue fixed or not

**Comment by D024kkk** [comment]
Yes , the seek bar problem and expand button is fixed and **Thank You So Much** for that , & there is one more bug that the high quality videos like 4K and (1080p WEB DL) is not playing , Please fix this one also

**Comment by D024kkk** [comment]
Please try to add a new feature like Download Manager, because when we download a video it doesn't show that it is downloading, and there is no download folder , and so we can't pause or resume the downloading 
Please add download manager like **1DM** if it is possible 

Please 🙏🙏🥺

**Comment by Zenda-Cross** [comment]
external downloader feature is already there. 
Hold the download button it will show a popup and then click on any server. It will ask to open in IDM or FDM, whatever you have installed on your device.

**Comment by D024kkk** [comment]
**Thank You**

**Comment by D024kkk** [comment]
Can you please try to add more websites in the app 

**> Bollyflix 
> Hdmovie2
> HDMovies4u
> KatMovieHD**

Because some movies are not available in those websites

**Comment by Zenda-Cross** [comment]
ok, I will try
