### ISSUE TITLE
Add other video player

### ISSUE THREAD

**Issue by Monuk2744** [Zenda-Cross/vega-app#69]
Add other video player like Gv player 
Vlc player doesn't work uhdmovies and other providers link and I use mx player pro mod its not open sometime on Android tv

**Comment by Monuk2744** [comment]
Ok and add android tv remote control not working

**Comment by Zenda-Cross** [comment]
Yeah, currently, there is no TV support. I want to work on it, but just not getting enough time.

**Comment by Monuk2744** [comment]
no big deal, just add the video player like Gv player

**Comment by Zenda-Cross** [comment]
Video player support added https://github.com/Zenda-Cross/vega-app/releases/tag/v2.3.0

**Comment by Monuk2744** [comment]
Thanks bro for video players, improve android tv support remote👍👍👍
