### ISSUE TITLE
Downloads setting not working

### ISSUE THREAD

**Issue by Parasgaming122** [Zenda-Cross/vega-app#75]
Android 9 
Infinix  x627

Uploading 20240816200557.mp4…

**Comment by Parasgaming122** [comment]
https://dood.li/d/tvtpmluw3s14 if the video doesn't display this is the link

**Comment by Zenda-Cross** [comment]
Sorry, I didn't understand what you meant.

**Comment by Parasgaming122** [comment]
The download folder setting doesnt open unlike preference captions when we press the button nothing happens

**Comment by Zenda-Cross** [comment]
ok

**Comment by Zenda-Cross** [comment]
looks like permission issue, storage permission works differently below Android 10 
Try giving storage permission to the app from settings.

**Comment by Parasgaming122** [comment]
now it works but gets not responding and turns off the app

**Comment by Zenda-Cross** [comment]
sorry ,wasn't able to reproduce the issue
for now you can open it manual way
