### ISSUE TITLE
Please  version ios  ipa and xcode 2024

### ISSUE THREAD

**Issue by popcorn2024ok** [Zenda-Cross/vega-app#81]
I can't install vega-app on my ipad with xcode I can only install on my android is there a solution or can I install with xcode without having any problem installing with xcode with my ipad pro if there is a solution with an ipa to install easier with an ipa for ios and ipad pro it is easier until the xcode problem is solved to be able to install vegamovie and it is solved soon with xcode  year 2024 agust 18

**Comment by Zenda-Cross** [comment]
Building for iOS would be challenging now because the app uses many packages that only work for Android so that code needed to be handled with platform-specific code.
