### ISSUE TITLE
External player

### ISSUE THREAD

**Issue by Mrunknow3** [Zenda-Cross/vega-app#82]
When I enable an external player setting and open any media that opens the download link in my soul browser. 

I have 2 players but mx player and gv player.

**Comment by Zenda-Cross** [comment]
maybe its because you have set Soul Browser as default application to open online streams

**Comment by Mrunknow3** [comment]
Now it's working with players. 

I have a suggestion to make a telegram group of your app.

**Comment by Zenda-Cross** [comment]
> I have a suggestion to make a telegram group of your app. 

There's already discord server

**Comment by Mrunknow3** [comment]
Ok no problem

**Comment by Mrunknow3** [comment]
Ok no problem
