### ISSUE TITLE
Provider Request

### ISSUE THREAD

**Issue by OshekharO** [Zenda-Cross/vega-app#88]
Yomovies: https://github.com/miru-project/repo/blob/main/repo/yomovies.js

Kisshk: https://github.com/miru-project/repo/blob/main/repo/kisskh.co.js

**Comment by Zenda-Cross** [comment]
sorry but I can't take more provider requests for now I am already at limit

**Comment by OshekharO** [comment]
> sorry but I can't take more provider requests for now I am already received many requests that's it practically not possible

Kisshk is api based so I think it's more practical and easier to add for you?

**Comment by Zenda-Cross** [comment]
oh that would be easy, I will try that

**Comment by Harsh74170** [comment]
Can u add olamovies.baby also

**Comment by Zenda-Cross** [comment]
> Can u add olamovies.baby also

Its not possible to add olamovies.
Join discord if you want more info on that.
