### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by D024kkk** [Zenda-Cross/vega-app#90]
Add a **trailer option** in app so we can play hindi trailer directly from app before watching any movie

**Comment by Zenda-Cross** [comment]
I think there isn't much space for it.
Maybe I could make a discord pole if more people want it.

**Comment by D024kkk** [comment]
You can simply insert the youtube link above the name of the movie where thumbnail is appeared

**Comment by Zenda-Cross** [comment]
thanks for the suggestion I will try it.

**Comment by D024kkk** [comment]
Ok thanks
