### ISSUE TITLE
Watch history 

### ISSUE THREAD

**Issue by FaqatZubair1** [Zenda-Cross/vega-app#98]
### Describe your suggested feature

There should be a "recently watched" or "continue watching" section in the app. So that I can carry on watching from where I left.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by FaqatZubair1** [comment]
Sorry, I just found it in the settings, but honestly I don't know how it works and where can I access the menu, because it doesn't show up any where.

**Comment by Zenda-Cross** [comment]
Restart the app after enabling it.
Then recently watched movies should show on top row at homepage

**Comment by FaqatZubair1** [comment]
![Screenshot_20240901-174511](https://github.com/user-attachments/assets/578c6c17-a42e-4570-a16b-42712caaf2d9)
Idk what is happening, here's the screenshot of my homepage. I'm currently watching a web series and am already on 3rd episode, and I can't find recently watched anywhere, help!

**Comment by FaqatZubair1** [comment]
It magically started working, I guess my phone hadn't cleared it from RAM earlier.
Thanks for your work. 🩷
